@startuml apprunner

!$AWS_DARK = false

left to right direction


!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v17.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Groups/all.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Groups/Region.puml
!include AWSPuml/NetworkingContentDelivery/VirtualPrivateCloud.puml

!include AWSPuml/Compute/AppRunner.puml
!include AWSPuml/Containers/all.puml
!include AWSPuml/Containers/ElasticContainerRegistryImage.puml

' Groups are rectangles with a custom style using stereotype - need to hide
hide stereotype
skinparam linetype ortho
skinparam rectangle {
    BackgroundColor AWS_BG_COLOR
    BorderColor transparent
    Shadowing false
}

AWSCloudGroup(aws_cloud, "AWS Cloud") {
    RegionGroup(aws_region, "us-east-1") {
        VirtualPrivateCloud(vpc, "VPC", "Amazon VPC") {
            AppRunner(api, "API service", "NodeJS")
            AppRunner(fe, "Frontend service", "NuxtJS")
        }
        ElasticContainerRegistry(ecr_api, "ECR", "No    deJS") {
            ElasticContainerRegistryImage(api_ecr_image, "API Container image", "NodeJSs")
        }
        ElasticContainerRegistry(ecr_fe, "ECR", "NuxtJS") {
            ElasticContainerRegistryImage(fe_ecr_image, "FE Container image", "NodeJSs")
        }
    }
}

ingress <-[dashed,$AWS_COLOR_GALAXY]u----> fe


'ECR Image to AppRunner '
api_ecr_image -[$AWS_COLOR_SMILE]----> api : pull container image
fe_ecr_image -[$AWS_COLOR_SMILE]----> fe : pull container image

'AppRunner to AppRunner '
fe -[$AWS_COLOR_SMILE]-> api

'Positioning'
ecr_api -[hidden]left--------> ecr_fe
vpc -[hidden]up--> fe
vpc -[hidden]down--> api

@enduml
